export const HOME_PATH ="/";
export const SIGNIN_PATH = "/signin";
export const SIGNUP_PATH = "/signup";
export const SHOW_ALL_PETS = "/pets";
export const SHOW_ADOPT_PET_REQUEST = "/show_adoptions";
export const SEND_DONATE_PET_REQUEST = "/donation";
export const SHOW_DONATE_PET_REQUEST = "/show_donations";
export const FILL_DONATION_FORM = "/donation_form/:petId"
export const USER_PROFILE= "/profile"
export const ABOUT_US= "/about"
export const NOT_FOUND = "*"; 
